package com.sentinelshield.data.models

/**
 * Represents a threat alert generated by the AI engine or scanner.
 */
data class ThreatAlert(
    val packageName: String,
    val appName: String,
    val threatLevel: ThreatLevel,
    val description: String,
    val recommendation: String,
    val timestamp: Long = System.currentTimeMillis(),
    val source: String = "ai_engine"  // "ai_engine", "scanner", "behavioral", "phishing"
)

enum class ThreatLevel {
    LOW,
    MEDIUM,
    HIGH,
    CRITICAL
}
